<?php
/**
 * CreateCombinedSubmissionBodyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  FormAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API V1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace FormAPI;

/**
 * CreateCombinedSubmissionBodyTest Class Doc Comment
 *
 * @category    Class */
// * @description CreateCombinedSubmissionBody
/**
 * @package     FormAPI
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateCombinedSubmissionBodyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CreateCombinedSubmissionBody"
     */
    public function testCreateCombinedSubmissionBody()
    {
    }

    /**
     * Test attribute "test"
     */
    public function testPropertyTest()
    {
    }

    /**
     * Test attribute "submission_ids"
     */
    public function testPropertySubmissionIds()
    {
    }

    /**
     * Test attribute "metadata"
     */
    public function testPropertyMetadata()
    {
    }

    /**
     * Test attribute "expires_in"
     */
    public function testPropertyExpiresIn()
    {
    }
}
