<?php
/**
 * SubmissionBatchTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  FormAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API v1
 *
 * FormAPI is a service that helps you fill out and sign PDF templates.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FormAPI;

/**
 * SubmissionBatchTest Class Doc Comment
 *
 * @category    Class
 * @description SubmissionBatch
 * @package     FormAPI
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SubmissionBatchTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SubmissionBatch"
     */
    public function testSubmissionBatch()
    {
    }

    /**
     * Test attribute "pending_count"
     */
    public function testPropertyPendingCount()
    {
    }

    /**
     * Test attribute "completion_percentage"
     */
    public function testPropertyCompletionPercentage()
    {
    }

    /**
     * Test attribute "metadata"
     */
    public function testPropertyMetadata()
    {
    }

    /**
     * Test attribute "total_count"
     */
    public function testPropertyTotalCount()
    {
    }

    /**
     * Test attribute "submissions"
     */
    public function testPropertySubmissions()
    {
    }

    /**
     * Test attribute "processed_at"
     */
    public function testPropertyProcessedAt()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "error_count"
     */
    public function testPropertyErrorCount()
    {
    }
}
