<?php
/**
 * Template1Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  FormAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API v1
 *
 * FormAPI is a service that helps you fill out and sign PDF templates.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FormAPI;

/**
 * Template1Test Class Doc Comment
 *
 * @category    Class
 * @description Template1
 * @package     FormAPI
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class Template1Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Template1"
     */
    public function testTemplate1()
    {
    }

    /**
     * Test attribute "expiration_interval"
     */
    public function testPropertyExpirationInterval()
    {
    }

    /**
     * Test attribute "webhook_url"
     */
    public function testPropertyWebhookUrl()
    {
    }

    /**
     * Test attribute "expire_after"
     */
    public function testPropertyExpireAfter()
    {
    }

    /**
     * Test attribute "allow_additional_properties"
     */
    public function testPropertyAllowAdditionalProperties()
    {
    }

    /**
     * Test attribute "public_submissions"
     */
    public function testPropertyPublicSubmissions()
    {
    }

    /**
     * Test attribute "slack_webhook_url"
     */
    public function testPropertySlackWebhookUrl()
    {
    }

    /**
     * Test attribute "blockchain_timestamp_verification"
     */
    public function testPropertyBlockchainTimestampVerification()
    {
    }

    /**
     * Test attribute "public_web_form"
     */
    public function testPropertyPublicWebForm()
    {
    }

    /**
     * Test attribute "expire_submissions"
     */
    public function testPropertyExpireSubmissions()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "template_type"
     */
    public function testPropertyTemplateType()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "redirect_url"
     */
    public function testPropertyRedirectUrl()
    {
    }
}
