<?php
/**
 * UpdateSubmissionDataRequestDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  FormAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API v1
 *
 * FormAPI is a service that helps you fill out and sign PDF templates.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FormAPI;

/**
 * UpdateSubmissionDataRequestDataTest Class Doc Comment
 *
 * @category    Class
 * @description UpdateSubmissionDataRequestData
 * @package     FormAPI
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class UpdateSubmissionDataRequestDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UpdateSubmissionDataRequestData"
     */
    public function testUpdateSubmissionDataRequestData()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "order"
     */
    public function testPropertyOrder()
    {
    }

    /**
     * Test attribute "fields"
     */
    public function testPropertyFields()
    {
    }

    /**
     * Test attribute "metadata"
     */
    public function testPropertyMetadata()
    {
    }

    /**
     * Test attribute "auth_type"
     */
    public function testPropertyAuthType()
    {
    }

    /**
     * Test attribute "auth_second_factor_type"
     */
    public function testPropertyAuthSecondFactorType()
    {
    }

    /**
     * Test attribute "auth_provider"
     */
    public function testPropertyAuthProvider()
    {
    }

    /**
     * Test attribute "auth_session_started_at"
     */
    public function testPropertyAuthSessionStartedAt()
    {
    }

    /**
     * Test attribute "auth_session_id_hash"
     */
    public function testPropertyAuthSessionIdHash()
    {
    }

    /**
     * Test attribute "auth_user_id_hash"
     */
    public function testPropertyAuthUserIdHash()
    {
    }

    /**
     * Test attribute "auth_username_hash"
     */
    public function testPropertyAuthUsernameHash()
    {
    }

    /**
     * Test attribute "auth_phone_number_hash"
     */
    public function testPropertyAuthPhoneNumberHash()
    {
    }
}
